### ISSUE TITLE
The parameters aren't clear ! And how does the output look like ?

### ISSUE THREAD

**Issue by minanagehsalalma** [akabe1/kr00ker#1]
-c
 -n <num-packets> -r <reason-id> 
-d <delay>
Why do i need -c when attacking an ap ?

A vid would be very useful.

**Comment by akabe1** [comment]
Ok this is not what I call properly an issue. However, I try to answer you in order to make you more curious about the 802.11 standard.
The -c parameter is used because to build an 802.11 frame you need the mac addresses of both nodes. The other parameters are explained in the help, however: -r specifies the reason value for the disassociation frames (for the standard the reason can assume different values and each value has a precise meaning); the script provides a cycle in which it sends -n frame disassociation with a time interval equal to -d.

**Comment by minanagehsalalma** [comment]
> you need the mac addresses of both nodes

You mean the adapter? 

Can we get a pic of the output?   I can't test it this while ;(
