### ISSUE TITLE
Lol i though that this was KRACK..

### ISSUE THREAD

**Issue by minanagehsalalma** [akabe1/kr00ker#2]
My mistake.

But can we get a one for it as the available script is just for testing and will only tell you if you  are vunrable or not ... without extracting any data....

Also i think this one is pretty useless as getting the last packets before the connection is gone can't get you a good use in the most of the time.

**Comment by akabe1** [comment]
Yes this is different from KRACK. For more details I suggest you to read the document linked in the References and watch also the [ESET video presentation](https://www.youtube.com/watch?v=_40E6WRMRyE).

In this presentation is explained how an attacker could extract decrypted data from vulnerable devices via the Kr00k exploitation. For this purpose this script send continuously the disassociation packets in order to catch, frame by frame, the decrypted data (if something has been buffered in the vulnerable device). And if you run the script against a vuln device you can see that it extract the plaintext data (printed as hexdump) and also save it in a pcap.  
Obviously if the victim is using an encrypted channel as TLS, you can not read it.

I would like to emphasize that the purpose of the script is not to steal data or cause damage to others, but only to help you identify if your devices are vulnerable.

**Comment by minanagehsalalma** [comment]
@akabe1 hmmm.... is it possible to get the router ip using it ?  And how long does it take mostly?
